[package]
name = "client"
version = "0.1.0"
edition = "2015"

[dependencies]
rusty_docs = { path = "../rusty_docs" }
rand = "0.8"
gtk4 = { version = "0.9.6", package = "gtk4" }
relm4 = "0.9.1"
gdk4 = "0.9.6"
chrono = "0.4.41"
