[package]
name = "llm_microservice"
version = "0.1.0"
edition = "2015"

[dependencies]
rusty_docs = { path = "../rusty_docs" }
reqwest = { version = "0.11", features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0"
