[package]
name = "rusty-docs"
version = "0.1.0"


[dependencies]
gtk4 = { version = "0.9.6", package = "gtk4" }
relm4 = { version = "0.9.1" }
gdk4 = { version = "0.9.6" }

#[[bin]]
#name = "client"
#path = "src/client.rs"

#[[bin]]
#name = "node"
#path = "src/node.rs"