services:
  node0:
    build: .
    image: redis-node
    container_name: node0
    working_dir: /usr/local/bin
    ports:
      - "14000:14000"
    volumes:
      - ./redis_server/conf_files:/usr/local/bin/redis_server/conf_files
      - ./redis_server/rdb_files:/usr/local/bin/redis_server/rdb_files
    command: ["redis_server_bin", "4000"]

  node1:
    build: .
    image: redis-node
    container_name: node1
    working_dir: /usr/local/bin
    ports:
      - "14001:14001"
    volumes:
      - ./redis_server/conf_files:/usr/local/bin/redis_server/conf_files
      - ./redis_server/rdb_files:/usr/local/bin/redis_server/rdb_files
    command: ["redis_server_bin", "4001"]

  node2:
    build: .
    image: redis-node
    container_name: node2
    working_dir: /usr/local/bin
    ports:
      - "14002:14002"
    volumes:
      - ./redis_server/conf_files:/usr/local/bin/redis_server/conf_files
      - ./redis_server/rdb_files:/usr/local/bin/redis_server/rdb_files
    command: ["redis_server_bin", "4002"]
