services:
  redis-node-0:
    image: redis-node
    container_name: redis-node-0
    working_dir: /usr/local/bin
    ports:
      - "4000:4000"
    volumes:
      - ./redis_server/conf_files:/usr/local/bin/redis_server/conf_files
      - ./redis_server/rdb_files:/usr/local/bin/redis_server/rdb_files
    command: ["redis_server_bin", "4000"]

  redis-node-1:
    image: redis-node
    container_name: redis-node-1
    working_dir: /usr/local/bin
    ports:
      - "4001:4001"
    volumes:
      - ./redis_server/conf_files:/usr/local/bin/redis_server/conf_files
      - ./redis_server/rdb_files:/usr/local/bin/redis_server/rdb_files
    command: ["redis_server_bin", "4001"]

  redis-node-2:
    image: redis-node
    container_name: redis-node-2
    working_dir: /usr/local/bin
    ports:
      - "4002:4002"
    volumes:
      - ./redis_server/conf_files:/usr/local/bin/redis_server/conf_files
      - ./redis_server/rdb_files:/usr/local/bin/redis_server/rdb_files
    command: ["redis_server_bin", "4002"]
